server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Shubhu@242424
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true


  security:
    user:
      name: user
      password: password


